### ISSUE TITLE
Cross Platform Support?

### ISSUE THREAD

**Issue by corymosiman12** [hyperjeff/Physical#1]
Hi Jeff,

Just saw your recent talk: https://www.youtube.com/watch?v=xmD8wUZ0egQ. I haven't played around with your API yet, but it looks incredibly usable. Your target platforms are all Apple specific - is it at all on your radar to add support for Linux (hardware accelerated or not)?

Having worked with Apple's Measurement framework, unit APIs in [Project Haystack](https://project-haystack.org/doc/docHaystack/Units) / and [Fantom](https://fantom.org/doc/sys/Unit) as well as colleagues of mine rolling our own (https://github.com/NeedleInAJayStack/Units), the wrapping together of the numerical uncertainty issues, physically meaningful constants, etc. is a nice touch - thanks for putting this together.

If you think this discussion belongs somewhere else, happy to move out of issues - just needed some mechanism to contact.

**Comment by hyperjeff** [comment]
Hi! Yes, this is something that I was hoping to have time to make available on all platforms. It will take some careful work to re-implement the core part of the Measurement system, dropping the localization part, at least at first, but perhaps there are opportunities to improve on it as well. I'm sure alternatives for vectorization will take some thought as well. I think those are the only two sticking points.

Thanks for the vote on this direction. I didn't know if non-Apple platform support was of interest to others or not.

**Comment by hyperjeff** [comment]
Cross-platform support will be a target for a future release. Closing this issue for now.
